### PR TITLE
Added application lifetime objects for Windows Phone

### PR DESCRIPTION
**Pull request by lothrop**

### CODE REVIEW

**Comment by lothrop** [comment]
Set minimum iOS version for Unified API projects to 5.1.1.

**Comment by asudbury** [comment]
I have looked at what the Xamarin minimum version is they use in their templates - its 6.0 - I was going to bump up to 6.0 for both classic and unified would that be ok @Lothrop ?

**Comment by lothrop** [comment]
I only tested that it works with 5.1.1. Anything below will now result in a compilation error in Xamarin.iOS 8.6. You can use 6.0 if you like. Anything below that it pretty much irrelevant now and it's not as if the user couldn't modify that number anymore.
